#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "\${PS1:-}" ]; then
    PS1=__dummy__
fi
. $(cd /home/exx/jiatong/projects/svs/Muskits/tools/anaconda; pwd)/etc/profile.d/conda.sh && conda deactivate && conda activate svs
