#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /data3/qt/Muskits/tools/venv/etc/profile.d/conda.sh && conda deactivate && conda activate /data3/qt/Muskits/tools/anaconda/envs/muskit
