#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /root/data/hku_kg_cuda/NanHUO_HKU/Muskits_3/Muskits/tools/anaconda/etc/profile.d/conda.sh && conda deactivate && conda activate muskit_3
